### ISSUE TITLE
Question about dataset

### ISSUE THREAD

**Issue by yxhhxy7** [XiaofeiWang2018/DeepGF#1]
Hi,

Thanks for sharing the code of this great work. Would you like to share the password of the dataset you uploaded in dropbox? 
Please contact me if possible (yxhhxy1999@gmail.com).

Thanks.

**Comment by XiaofeiWang2018** [comment]
ric207 xiaofei wang 邮箱：wangxiaofei2018@gmail.com 签名由 网易邮箱大师 定制 On 02/27/2021 22:16, yxhhxy7 wrote: Hi, Thanks for sharing the code of this great work. Would you like to share the password of the dataset you uploaded in dropbox? Please contact me if possible (yxhhxy1999@gmail.com). Thanks. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
