### ISSUE TITLE
Question about code

### ISSUE THREAD

**Issue by yxhhxy7** [XiaofeiWang2018/DeepGF#3]
你好，

非常感谢您发布的代码。

我在看train.py的时候发现网络输出了五个label。根据论文里说的forecast的目标，是不是应该输出一个未来的年份的label呢？
请问是不是我哪里弄错了？

谢谢！

**Comment by XiaofeiWang2018** [comment]
你好 输出的是多个label没错，每个label都是对应图片的未来态，也就是多个图片forecast的 labels. 祝好 xiaofei wang 邮箱：wangxiaofei2018@gmail.com 签名由 网易邮箱大师 定制 On 03/08/2021 15:49, yxhhxy7 wrote: 你好， 非常感谢您发布的代码。 我在看train.py的时候发现网络输出了五个label。根据论文里说的forecast的目标，是不是应该输出一个未来的年份的label呢？ 请问是不是我哪里弄错了？ 谢谢！ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by yxhhxy7** [comment]
> 你好 输出的是多个label没错，每个label都是对应图片的未来态，也就是多个图片forecast的 labels. 祝好 xiaofei wang 邮箱：wangxiaofei2018@gmail.com 签名由 网易邮箱大师 定制 On 03/08/2021 15:49, yxhhxy7 wrote: 你好， 非常感谢您发布的代码。 我在看train.py的时候发现网络输出了五个label。根据论文里说的forecast的目标，是不是应该输出一个未来的年份的label呢？ 请问是不是我哪里弄错了？ 谢谢！ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

好的谢谢您，我再看一下。

**Comment by jwzxgy2007** [comment]
你好！论文里面说的将405个序列clip成了1000多个序列，这一步有代码吗，谢谢~

**Comment by XiaofeiWang2018** [comment]
你好， 请参考开源的数据库的文件。

**Comment by jwzxgy2007** [comment]
> 你好， 请参考开源的数据库的文件。

你好，开源的数据库里面是405个序列，没有代码里里面的all文件夹，怎么处理得到all的代码没有找到，应该是怎么处理呢

**Comment by XiaofeiWang2018** [comment]
你好， 正如论文所说，连续的6个slice就是一份，如果一个文件夹里有8个，那么就有3个序列，以此类推


Lingxiao Zhang <notifications@github.com> 于2021年3月10日周三 上午11:36写道：
